resolver: lts-10.4
extra-deps:
- yesod-core-1.6.1
- conduit-1.3.0
- conduit-extra-1.3.0
- resourcet-1.2.0
- mono-traversable-1.0.8.1
- typed-process-0.2.1.0
- monad-logger-0.3.28.1
- wai-extra-3.0.22.0
- cookie-0.4.3
- unliftio-0.2.4.0
- unliftio-core-0.1.1.0
- aeson-1.2.4.0
- th-abstraction-0.2.6.0
- simple-sendfile-0.2.27
